# Generated by Django 3.1.8 on 2023-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tv_series", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="netflix_seires",
            name="test",
            field=models.TextField(default="test"),
        ),
    ]
