FROM ubuntu:20.04

RUN apt update && apt install -y python3 python3-pip

RUN mkdir code

WORKDIR /code

COPY . src/

RUN pip3 install -r src/requirements.txt

CMD [ "uwsgi","--py-autoreload","1","--http",":8000" ,"--module" ,"api_crud.wsgi" ]

